name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "*/12 * * * *"
  workflow_dispatch:

env: 
  NODE_VERSION: '16.x'

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Snake Action
        uses: Platane/snk@v0.5.1
        with:
          github_user_name: MatheusGoncalvx
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          build_dir: dist
          branch: main # branch para o deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
