name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Generate snake animation
        uses: Platane/snk@v0.4.0
        with:
          github_user_name: MatheusGoncalvx
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.1.2
        with:
          target_branch: main
          build_dir: dist
          publish_dir: dist
          cname: github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
