name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

env: 
  NODE_VERSION: '16.x'

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: MatheusGoncalvx
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3.7.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Output
        run: |
          echo "::set-env name=OUTPUT_URL::https://${{ github.repository }}/output/"
        shell: bash
      - name: Get Output URL
        id: output_url
        run: echo "${{ env.OUTPUT_URL }}"
      - name: Output URL
        run: echo "Output URL is ${{ steps.output_url.outputs.OUTPUT_URL }}"
